spring:
  application:
    name: pbs-mail-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pbs_mail_service_db?currentSchema=gnl_pbs_ogs
    username: postgres
    password: oyas1230
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: "http://zipkin:9411"

server:
  port: 8300

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Observability & Monitoring
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0
    enabled: true